CC = gcc
CFLAGS = -Wall -Werror -Wextra
TARGET = Simu
SOURCE = BlueKernel_lvl3.c
OBJECTS = $(SOURCE:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -c  $< -o $@

clean:
	rm -f $(OBJECTS) $(TARGET)
